# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='healthinfo.proto',
  package='Navtech.Core.Configuration.Protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10healthinfo.proto\x12#Navtech.Core.Configuration.Protobuf\"\xfb\x01\n\nHealthInfo\x12\x15\n\x08minvalue\x18\x01 \x01(\x02:\x03-10\x12\x14\n\x08maxvalue\x18\x02 \x01(\x02:\x02\x31\x30\x12\x10\n\x05value\x18\x03 \x01(\x02:\x01\x30\x12\x10\n\x05\x64\x65lta\x18\x04 \x01(\x02:\x01\x30\x12J\n\x06status\x18\x05 \x01(\x0e\x32\x31.Navtech.Core.Configuration.Protobuf.HealthStatus:\x07UNKNOWN\x12\x19\n\rwarnallowance\x18\x06 \x01(\x05:\x02\x31\x32\x12\x1a\n\x0e\x61larmallowance\x18\x07 \x01(\x05:\x02\x32\x30\x12\x19\n\x0e\x63learallowance\x18\x08 \x01(\x05:\x01\x31*D\n\x0cHealthStatus\x12\r\n\tUNHEALTHY\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\x0b\n\x07HEALTHY\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03')
)

_HEALTHSTATUS = _descriptor.EnumDescriptor(
  name='HealthStatus',
  full_name='Navtech.Core.Configuration.Protobuf.HealthStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNHEALTHY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTHY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=311,
  serialized_end=379,
)
_sym_db.RegisterEnumDescriptor(_HEALTHSTATUS)

HealthStatus = enum_type_wrapper.EnumTypeWrapper(_HEALTHSTATUS)
UNHEALTHY = 0
WARNING = 1
HEALTHY = 2
UNKNOWN = 3



_HEALTHINFO = _descriptor.Descriptor(
  name='HealthInfo',
  full_name='Navtech.Core.Configuration.Protobuf.HealthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minvalue', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.minvalue', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxvalue', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.maxvalue', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.delta', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warnallowance', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.warnallowance', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=12,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarmallowance', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.alarmallowance', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clearallowance', full_name='Navtech.Core.Configuration.Protobuf.HealthInfo.clearallowance', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=309,
)

_HEALTHINFO.fields_by_name['status'].enum_type = _HEALTHSTATUS
DESCRIPTOR.message_types_by_name['HealthInfo'] = _HEALTHINFO
DESCRIPTOR.enum_types_by_name['HealthStatus'] = _HEALTHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthInfo = _reflection.GeneratedProtocolMessageType('HealthInfo', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHINFO,
  __module__ = 'healthinfo_pb2'
  # @@protoc_insertion_point(class_scope:Navtech.Core.Configuration.Protobuf.HealthInfo)
  ))
_sym_db.RegisterMessage(HealthInfo)


# @@protoc_insertion_point(module_scope)
